### ISSUE TITLE
exceptions.AttributeError: 'module' object has no attribute 'get_ident'

### ISSUE THREAD

**Issue by jonnyyu** [tardyp/buildbot_profiler#3]
Running on buildbot0.9.8 on python 2.7.10 on MacOS.

It seems threading.get_ident() should be thread.get_ident()

2018-06-13 09:43:13-0700 [-] Unhandled Error                                                                                                                                                               │
        Traceback (most recent call last):                                                                                                                                                                 │
          File "/usr/local/lib/python2.7/site-packages/twisted/scripts/_twistd_unix.py", line 268, in postApplication                                                                                      │
            self.startReactor(None, self.oldstdout, self.oldstderr)                                                                                                                                        │
          File "/usr/local/lib/python2.7/site-packages/twisted/application/app.py", line 399, in startReactor                                                                                              │
            self.config, oldstdout, oldstderr, self.profiler, reactor)                                                                                                                                     │
          File "/usr/local/lib/python2.7/site-packages/twisted/application/app.py", line 312, in runReactorWithLogging                                                                                     │
            reactor.run()                                                                                                                                                                                  │
          File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1261, in run                                                                                                        │
            self.mainLoop()                                                                                                                                                                                │
        --- <exception caught here> ---                                                                                                                                                                    │
          File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1273, in mainLoop                                                                                                   │
            self.doIteration(t)                                                                                                                                                                            │
          File "/usr/local/lib/python2.7/site-packages/twisted/internet/epollreactor.py", line 218, in doPoll                                                                                              │
            l = self._poller.poll(timeout, len(self._selectables))                                                                                                                                         │
          File "/usr/local/lib/python2.7/site-packages/buildbot_profiler/api.py", line 94, in handler                                                                                                      │
            current_tid = threading.get_ident()                                                                                                                                                            │
        exceptions.AttributeError: 'module' object has no attribute 'get_ident'

**Comment by RomanSharapov** [comment]
Should be fixed in v1.2.3.
@tardyp, could you upload this version to pip?
