### ISSUE TITLE
Dependency to the future module must be expressed explicitly

### ISSUE THREAD

**Issue by vstinner** [tardyp/buildbot_profiler#7]
When I updated buildbot, I got the following error:

```
buildbot.errors.PluginDBError: Unable to load buildbot.www:profiler: No module named 'future'
```

Traceback:

<details>

```
2024-03-05 15:16:05+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "buildbot.tac", line 30, in <module>
	    m = BuildMaster(basedir, configfile, umask)
	  File "/srv/buildbot/venv/lib/python3.9/site-packages/buildbot/master.py", line 227, in startService
	    yield self._services_d
	  File "/srv/buildbot/venv/lib/python3.9/site-packages/twisted/internet/defer.py", line 2000, in _inlineCallbacks
	    result = context.run(gen.send, result)
	  File "/srv/buildbot/venv/lib/python3.9/site-packages/buildbot/master.py", line 188, in create_child_services
	    self.www = wwwservice.WWWService()
	  File "/srv/buildbot/venv/lib/python3.9/site-packages/buildbot/www/service.py", line 198, in __init__
	    self.apps = get_plugins('www', None, load_now=True)
	  File "/srv/buildbot/venv/lib/python3.9/site-packages/buildbot/plugins/db.py", line 367, in get_plugins
	    return _DB.add_namespace(namespace, interface, load_now)
	  File "/srv/buildbot/venv/lib/python3.9/site-packages/buildbot/plugins/db.py", line 317, in add_namespace
	    tempo.load()
	  File "/srv/buildbot/venv/lib/python3.9/site-packages/buildbot/plugins/db.py", line 254, in load
	    self._tree.load()
	  File "/srv/buildbot/venv/lib/python3.9/site-packages/buildbot/plugins/db.py", line 131, in load
	    child.load()
	  File "/srv/buildbot/venv/lib/python3.9/site-packages/buildbot/plugins/db.py", line 60, in load
	    self._value = self._loader(self._entry)
	  File "/srv/buildbot/venv/lib/python3.9/site-packages/buildbot/plugins/db.py", line 232, in _load_entry
	    raise PluginDBError(f'Unable to load {self._group}:{entry.name}: {str(e)}') from e
	buildbot.errors.PluginDBError: Unable to load buildbot.www:profiler: No module named 'future'
```

</details>

Sadly, installing the future module (pip install future) in the virtual environment didn't solve the issue, whereas `import future` just works with the Python of the venv.

Can you please add a dependency to the future module in setup.py? Thanks in advance.

**Comment by tardyp** [comment]
Hi, I haven't work on buildbot since a long time. 

I don't think buildbot_profiler will work anymore with the new react UI.

I think they did recently change a bit the flow with future and six. this is probably what is biting you on this topic.

So if you don't really need to profile your bot I would suggest to just remove buildbot_profiler from your deps at the moment.

Cheers
Pierre

**Comment by vstinner** [comment]
Thanks for your advice. I wrote https://github.com/python/buildmaster-config/pull/471 to remove the plugin from Python buildbots.

**Comment by vstinner** [comment]
We removed the buildbot_profiler dependency. I see that the latest commit in this project was 4 years ago. But the dependency to future is not a big deal, I close the issue. Thanks for your project anyway!
